// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_a_c_soluciones/test/bloc/register/register_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_a_c_soluciones/model/register_request_model.dart'
    as _i6;
import 'package:flutter_a_c_soluciones/model/register_response_model.dart'
    as _i3;
import 'package:flutter_a_c_soluciones/repository/service_api_register.dart'
    as _i4;
import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRegisterResponseModel_1 extends _i1.SmartFake
    implements _i3.RegisterResponseModel {
  _FakeRegisterResponseModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [APIServiceRegister].
///
/// See the documentation for Mockito's code generation for more information.
class MockAPIServiceRegister extends _i1.Mock
    implements _i4.APIServiceRegister {
  MockAPIServiceRegister() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeClient_0(
          this,
          Invocation.getter(#client),
        ),
      ) as _i2.Client);

  @override
  _i5.Future<_i3.RegisterResponseModel> register(
          _i6.RegisterRequestModel? model) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [model],
        ),
        returnValue: _i5.Future<_i3.RegisterResponseModel>.value(
            _FakeRegisterResponseModel_1(
          this,
          Invocation.method(
            #register,
            [model],
          ),
        )),
      ) as _i5.Future<_i3.RegisterResponseModel>);
}
