// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_a_c_soluciones/test/bloc/task/task_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_a_c_soluciones/model/administrador/visits_model.dart'
    as _i2;
import 'package:flutter_a_c_soluciones/repository/task_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeVisitsModel_0 extends _i1.SmartFake implements _i2.VisitsModel {
  _FakeVisitsModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTaskResponse_1 extends _i1.SmartFake implements _i3.TaskResponse {
  _FakeTaskResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRepository extends _i1.Mock implements _i3.TaskRepository {
  MockTaskRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.VisitsModel> getTaskById(int? taskId) => (super.noSuchMethod(
        Invocation.method(
          #getTaskById,
          [taskId],
        ),
        returnValue: _i4.Future<_i2.VisitsModel>.value(_FakeVisitsModel_0(
          this,
          Invocation.method(
            #getTaskById,
            [taskId],
          ),
        )),
      ) as _i4.Future<_i2.VisitsModel>);

  @override
  _i4.Future<void> updateTaskState(
    int? taskId,
    String? state,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTaskState,
          [
            taskId,
            state,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i3.TaskResponse> getTasks({int? page = 1}) => (super.noSuchMethod(
        Invocation.method(
          #getTasks,
          [],
          {#page: page},
        ),
        returnValue: _i4.Future<_i3.TaskResponse>.value(_FakeTaskResponse_1(
          this,
          Invocation.method(
            #getTasks,
            [],
            {#page: page},
          ),
        )),
      ) as _i4.Future<_i3.TaskResponse>);
}
