// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_a_c_soluciones/test/bloc/report/report_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_a_c_soluciones/repository/report_repository.dart'
    as _i2;
import 'package:image_picker/image_picker.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeReportResponse_0 extends _i1.SmartFake
    implements _i2.ReportResponse {
  _FakeReportResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ReportRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockReportRepository extends _i1.Mock implements _i2.ReportRepository {
  MockReportRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> createMaintenanceSheet({
    required int? visitId,
    required String? introduccion,
    required String? detallesServicio,
    required String? observaciones,
    required String? estadoAntes,
    required String? descripcionTrabajo,
    required String? materialesUtilizados,
    required String? estadoFinal,
    required String? tiempoDeTrabajo,
    required String? recomendaciones,
    required String? fechaDeMantenimiento,
    _i4.XFile? fotoEstadoAntes,
    _i4.XFile? fotoEstadoFinal,
    _i4.XFile? fotoDescripcionTrabajo,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createMaintenanceSheet,
          [],
          {
            #visitId: visitId,
            #introduccion: introduccion,
            #detallesServicio: detallesServicio,
            #observaciones: observaciones,
            #estadoAntes: estadoAntes,
            #descripcionTrabajo: descripcionTrabajo,
            #materialesUtilizados: materialesUtilizados,
            #estadoFinal: estadoFinal,
            #tiempoDeTrabajo: tiempoDeTrabajo,
            #recomendaciones: recomendaciones,
            #fechaDeMantenimiento: fechaDeMantenimiento,
            #fotoEstadoAntes: fotoEstadoAntes,
            #fotoEstadoFinal: fotoEstadoFinal,
            #fotoDescripcionTrabajo: fotoDescripcionTrabajo,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> getPdfPathForVisit(int? visitId) => (super.noSuchMethod(
        Invocation.method(
          #getPdfPathForVisit,
          [visitId],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<_i2.ReportResponse> getVisitsWithReports({
    int? page = 1,
    int? perPage = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVisitsWithReports,
          [],
          {
            #page: page,
            #perPage: perPage,
          },
        ),
        returnValue: _i3.Future<_i2.ReportResponse>.value(_FakeReportResponse_0(
          this,
          Invocation.method(
            #getVisitsWithReports,
            [],
            {
              #page: page,
              #perPage: perPage,
            },
          ),
        )),
      ) as _i3.Future<_i2.ReportResponse>);
}
