import 'package:flutter_test/flutter_test.dart';
import 'package:bloc_test/bloc_test.dart';
import 'package:flutter_a_c_soluciones/bloc/report/report_bloc.dart';
import 'package:flutter_a_c_soluciones/repository/report_repository.dart'; // For VisitWithReport
import 'package:flutter_a_c_soluciones/model/administrador/visits_model.dart'; // For VisitsModel
import 'package:mockito/mockito.dart';
import 'package:mockito/annotations.dart';

import 'report_bloc_test.mocks.dart'; // Generated by build_runner

// Generate a MockReportRepository
@GenerateMocks([ReportRepository])
void main() {
  group('ReportBloc', () {
    late MockReportRepository mockReportRepository;

    setUp(() {
      mockReportRepository = MockReportRepository();
    });

    test('initial state is ReportInitial', () {
      final reportBloc = ReportBloc(reportRepository: mockReportRepository);
      expect(reportBloc.state, ReportInitial());
    });

    blocTest<ReportBloc, ReportState>(
      'emits [ReportLoading, ReportSuccess] when LoadReports is added and fetching is successful',
      build: () {
        when(mockReportRepository.getVisitsWithReports()).thenAnswer(
          (_) async => [
            VisitWithReport(
              visit: VisitsModel(
                id: 1,
                fechaProgramada: DateTime.now(),
                duracionEstimada: 60,
                estado: 'completada',
                notasPrevias: 'Notas previas',
                notasPosteriores: 'Notas posteriores',
                fechaCreacion: DateTime.now(),
                solicitudId: 1,
                tecnicoId: 1,
                servicioId: 1,
              ),
              pdfPath: 'path/to/report.pdf',
            ),
          ],
        );
        return ReportBloc(reportRepository: mockReportRepository);
      },
      act: (bloc) => bloc.add(LoadReports()),
      expect: () => [
        ReportLoading(),
        isA<ReportSuccess>(),
      ],
      verify: (_) {
        verify(mockReportRepository.getVisitsWithReports()).called(1);
      },
    );

    blocTest<ReportBloc, ReportState>(
      'emits [ReportLoading, ReportFailure] when LoadReports is added and fetching fails',
      build: () {
        when(mockReportRepository.getVisitsWithReports()).thenThrow(Exception('Failed to load reports'));
        return ReportBloc(reportRepository: mockReportRepository);
      },
      act: (bloc) => bloc.add(LoadReports()),
      expect: () => [
        ReportLoading(),
        const ReportFailure(error: 'Exception: Failed to load reports'),
      ],
      verify: (_) {
        verify(mockReportRepository.getVisitsWithReports()).called(1);
      },
    );
  });
}